config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:create]
  get 'signup', to: 'users#new'
  resources :organizations, except: [:new]
  resources :organizations, only: [:show] do
    resources :users, only: [:update]
    resources :shifts, only: [:index, :create, :edit, :destroy, :update]
  end
   get 'login', to: 'sessions#new'
   post 'login', to: 'sessions#create'
   delete 'logout', to: 'sessions#destroy'
   put 'leave-org', to: 'users#leave'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :users
    has_many :shifts, through: :users

    validates :name, :hourly_rate, presence: true
end

app/models/shift.rb
class Shift < ApplicationRecord
    belongs_to :user

    validates :start, :finish, :user_id, presence: true

    def date
        self.start.strftime('%m/%d/%Y')    
    end

    def time(time)
        time.strftime('%I:%M%p')
    end

    def hours
        math = (self.finish - self.start)
        # divide out seconds then subrtract break time
        math = (math / 60) - self.break.to_i
        #convert to hours
        (math / 60).round(4)
    end
end

app/models/user.rb
class User < ApplicationRecord
    belongs_to :organization, optional: true
    has_many :shifts

    validates :name, :email, :password, presence: true
    validates :email, uniqueness: true
    validates :password, length: { minimum: 6 }
    
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
    def show
        authenticate!
        @organization = Organization.find(params[:id])
    end

    def index
        @organizations = Organization.all
    end

    def edit
        authenticate!
        @organization = Organization.find(params[:id])
    end

    def update
        authenticate!
        @organization = Organization.find(params[:id])
        @organization.name = params[:name]
        @organization.hourly_rate = params[:hourly_rate]        
        if @organization.save
            redirect_to organization_path(@organization)
        else 
            flash[:error] = @organization.errors.full_messages.to_sentence
            render :edit
        end
    end

    def create 
        authenticate!
        if current_user.organization_id != nil
            flash[:error] = "Please quit your current job before starting a business"
            redirect_to organizations_path
        else
            @organization = Organization.new(name: params[:name], hourly_rate: params[:hourly_rate])
            if @organization.save
                current_user.organization = @organization
                current_user.save(:validate => false)
                redirect_to organization_path(@organization)
            else 
                flash[:error] = @organization.errors.full_messages.to_sentence
                render :index 
            end
        end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def create
        @user = User.find_by(email: params[:email])
        if @user && @user.authenticate(params[:password])
            session[:id] = @user.id
            if @user.organization_id == nil
                redirect_to organizations_path
            else
                redirect_to organization_path(@user.organization)
            end
        else 
            @error = "Invalid credentials"
            render :new
        end
    end

    def destroy
        session[:id] = nil
        flash[:success] = "You have logged out!"
        redirect_to login_path
    end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
    def index
        authenticate!
        @organization = Organization.find(params[:organization_id])
        @shifts = @organization.shifts.order(:start)
    end

    def create
        p current_user.organization_id 
        p params[:organization_id]
        if current_user.organization_id == params[:organization_id].to_i
            @shift = Shift.new
            @shift.user = current_user
            @date = "#{params['date(3i)']}/#{params['date(2i)']}/#{params['date(1i)']}"
            @start = @date + " #{params['start(4i)']}:#{params['start(5i)']}"
            @finish = @date + " #{params['finish(4i)']}:#{params['finish(5i)']}"
            @shift.start = @start.to_datetime
            @shift.finish = @finish.to_datetime
            @shift.break = (params[:break]).to_i

            if @shift.save
                redirect_to organization_shifts_path(params[:organization_id])
            else
                flash[:error] = @shift.errors.full_messages.to_sentence
                redirect_to organization_shifts_path(params[:organization_id])
            end
        else
            flash[:error] = "You don't work here!"
            redirect_back(fallback_location: organizations_path)
        end
    end

    def edit
        @shift = Shift.find(params[:id])
        @organization = Organization.find(params[:organization_id])
        redirect_back(fallback_location: organization_shifts_path(@organization, @shift)) unless current_user.id == @shift.user_id
    end

    def update
        @shift = Shift.find(params[:id])
        redirect_back(fallback_location: organization_shifts_path(@organization, @shift)) unless current_user.id == @shift.user_id
        @date = "#{params['date(3i)']}/#{params['date(2i)']}/#{params['date(1i)']}"
        @start = @date + " #{params['start(4i)']}:#{params['start(5i)']}"
        @finish = @date + " #{params['finish(4i)']}:#{params['finish(5i)']}"
        @shift.start = @start.to_datetime
        @shift.finish = @finish.to_datetime
        @shift.break = (params[:break]).to_i

        if @shift.save
            redirect_to organization_shifts_path(params[:organization_id])
        else
            flash[:error] = @shift.errors.full_messages.to_sentence
            redirect_to organization_shifts_path(params[:organization_id])
        end
    end

    def destroy
        @shift = Shift.find(params[:id])
        if current_user.id == @shift.user_id
            @shift.destroy
        end
            redirect_to organization_shifts_path(params[:organization_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end


    def create
        @user = User.new(registration_params)
        if @user.save
            session[:id] = @user.id
            flash[:success] = "You have successfully Signed up"
            redirect_to organizations_path
        else
            @errors = @user.errors.full_messages
            render :new
        end
    end

    def update
        @user = User.find(params[:id])
        if @user.organization_id == nil
            @user.organization_id = params[:organization_id]
            @user.save(:validate => false)
            redirect_to organization_path(@user.organization)
        else
            flash[:error] = "You are already employed, please leave your other job first"
            redirect_to organizations_path
        end
    end

    def leave
        current_user.organization_id = nil
        current_user.save(:validate => false)
        current_user.shifts.destroy_all
        flash[:success] = "You have left the organization"
        redirect_to organizations_path
    end



    private 

    def registration_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionHelper
end

app/helpers/session_helper.rb
module SessionHelper
	
	def current_user
		@current_user ||= User.find_by(id: session[:id]) if session[:id]
	end

	def logged_in?
		session[:id] != nil
	end

	def authenticate!
    	redirect_to login_path unless logged_in?
	end

	def yours?
		redirect_back(fallback_location: organization_shifts_path(@organization, @shift)) unless current_user.id == @shift.user_id
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TandaRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !current_user %>
      <h1><%= link_to 'Adnat', login_path %></h1>
    <% else  %>
      <% if current_user.organization_id == nil %>
          <h1><%= link_to 'Adnat', organizations_path %></h1>
      <% else  %>
        <h1><%= link_to 'Adnat', organization_path(current_user.organization) %></h1>
      <% end %>
      
    <% end %>

    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash #{key}" %>
    <% end %>

    <% if current_user%>
      <p>You are logged in as <%= current_user.name %> <%= link_to "Log out", logout_path, method: :delete %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/organizations/_organization.html.erb
<div class="listed-org">
    <%= organization.name%>
    <%=link_to "Edit", edit_organization_path(organization)  %>
    <%= link_to "Join", organization_user_path(organization, current_user), method: :put %>
</div>

app/views/organizations/edit.html.erb
<h3>Edit Organization</h3>
<%= form_with url: organization_path(@organization), method: :patch, local: true do |f| %>
<div>
    <%= f.label :Name %>
    <%= f.text_field :name, value: @organization.name%>
</div>

<div>
    <%= f.label :Hourly_rate %> $
    <%= f.text_field :hourly_rate, value: @organization.hourly_rate%>
</div>

<div>
    <%= f.submit "Update" %>
</div>
<% end %>

app/views/organizations/index.html.erb
<% if current_user.organization_id == nil %> 
    <p>You are not a member of any Organization.  Join one or start your own!</p>
<% end %>
<h1>Organizations</h1>
<%= render @organizations %>

<h3>Create Organization</h3>
<%= form_with url: organizations_path, local: true do |f| %>
<div>
    <%= f.label :Name %>
    <%= f.text_field :name%>
</div>

<div>
    <%= f.label :Hourly_rate %> $
    <%= f.text_field :hourly_rate%>
</div>

<div>
    <%= f.submit "Create and Join" %>
</div>
<% end %>

app/views/organizations/show.html.erb
<h2><%= @organization.name%></h2>
<%=link_to "Shifts", organization_shifts_path(@organization) %>
<%=link_to "Edit", edit_organization_path(@organization)  %>
<% if current_user.organization_id == @organization.id %>
    <%=link_to "Leave", leave_org_path(current_user), method: :put  %>
<% end %>

app/views/shifts/_shift.html.erb
<tr> 
    <td><%= shift.user.name%></td>
    <td><%= shift.date %></td> 
    <td><%= shift.time(shift.start) %></td> 
    <td><%= shift.time(shift.finish) %></td> 
    <td><%= shift.break %></td>
    <td><%= shift.hours %></td>
    <td><%= number_to_currency((shift.hours * @organization.hourly_rate).round(2)) %></td>
    <% if current_user.id == shift.user_id %>
        <td><%= link_to 'Edit', edit_organization_shift_path(@organization, shift) %></td>
        <td><%= link_to 'Delete', organization_shift_path(@organization, shift), method: :delete %></td>
    <% end %>
</tr>

app/views/shifts/edit.html.erb
<%= form_with url: organization_shift_path(@organization, @shift), method: :put, local: true do |f| %>
<table>
  <tr>
    <th>Employee Name</th>
    <th>Shift Date</th>
    <th>Start Time</th>
    <th>Finish Time</th>
    <th>Break Length (minutes)</th>
    <th>Hours worked</th>
    <th>Shift Cost</th>
  </tr>
  <tr>
    <td>
      <%= current_user.name %>
    </td>
    <td>
      <%= f.date_select :date, order: [:month, :day, :year], default: @shift.start %>
    </td>

    <td>
      <%= f.time_select :start, default: @shift.start %>
    </td>

    <td>
      <%= f.time_select :finish, default: @shift.finish %>
    </td>

    <td>
      <%= f.text_field :break, value: @shift.break %>
    </td>

    <td colspan="2">
      <%= f.submit "Update Shift" %>
    </td>
  <tr>
</table>
<% end %>

app/views/shifts/index.html.erb
<table>
  <tr>
    <th>Employee Name</th>
    <th>Shift Date</th>
    <th>Start Time</th>
    <th>Finish Time</th>
    <th>Break Length (minutes)</th>
    <th>Hours worked</th>
    <th>Shift Cost</th>
  </tr>
  <%= render @shifts %>

  <tr>
    <%= form_with url: organization_shifts_path(@organization) , local: true do |f| %>
    <td>
      <%= current_user.name %>
    </td>
    <td>
      <%= f.date_select :date, :order => [:month, :day, :year] %>
    </td>

    <td>
      <%= f.time_select :start %>
    </td>

    <td>
      <%= f.time_select :finish %>
    </td>

    <td>
      <%= f.text_field :break %>
    </td>

    <td colspan="2">
      <%= f.submit "Create Shift" %>
    </td>
  <tr>
</table>

	<% end %>

app/views/users/new.html.erb
<div class="user-form">
	<h1>Sign Up</h1>
	<% if @errors %>
		<ul>
		<% @errors.each do |error| %>
			<li class="error"><%= error %> </li>
		<% end %>
		</ul>
	<%end%>
	<%= form_with model: @user, local: true do |f| %>
	<div>
        <%= f.label :Name %>
		<%= f.text_field :name%>
	</div>

	<div>
        <%= f.label :Email%>
		<%= f.email_field :email %>
	</div>

	<div>	
        <%= f.label :Password %>
		<%= f.password_field :password %>
	</div>

    <div>
        <%= f.label :Password_confirmation %>
		<%= f.password_field :password_confirmation%>
	</div>

	<div>
		<%= f.submit "Sign Up" %>
	</div>
	<% end %>
	<%= link_to 'Login', login_path %>
</div>